"""Gemini-compatible JSON Schema cleaning.

Gemini's ``FunctionDeclaration`` rejects extra JSON Schema fields that
are common in OpenAPI / MCP tool definitions (``$schema``,
``additionalProperties``, ``default``, ``title``).  This module
provides a recursive cleaner that strips unsupported fields while
preserving the structure Gemini expects.

Pydantic / FastAPI tool generators render ``Optional[X]`` parameters as
``{"anyOf": [{"type": X}, {"type": "null"}]}``. Naively stripping
``anyOf`` (because it is not in the allowed-key list) leaves the
property with no type at all — Gemini then silently refuses to invoke
the tool. This module collapses that pattern (and similar ``oneOf`` /
``allOf`` shapes) to ``{"type": X, "nullable": True}`` before stripping
unknown keys, so MCP tools generated by Pydantic round-trip cleanly
into Gemini Live function declarations.

The same optionality also arrives as a plain type list — ``{"type":
["string", "null"]}`` — which is what JSON Schema itself says and what
non-Pydantic generators emit (a TypeScript MCP server going through
``zod-to-json-schema``, for one). ``type`` is a key Gemini accepts, so
that list would survive the cleaning untouched and fail inside
``FunctionDeclaration``, whose ``type`` is a single-valued enum. It is
folded down the same way, so both spellings of "optional string" reach
Gemini as one.

Not every union is a choice between types. ``{"type": "object",
"properties": {...}, "oneOf": [{"required": ["url"]}, {"required":
["path"]}]}`` says "give url or path": its branches narrow the object they
sit on. Folding it to its first branch would replace the object with an
untyped fragment requiring a property it does not declare, and Gemini
refuses the whole request over one such tool. Such a union is kept out of
the fold: the object stays, with any field its branches add, and the union
goes the way of every other constraint Gemini cannot express.

JSON Schema also leaves things implied that Gemini needs spelled out: an
untyped node with ``properties`` is an object and one with ``items`` an
array, and an array may omit ``items``. Gemini refuses all three, so the
cleaner writes the type and gives a bare array ``items: {}``, "any value",
which is what Pydantic already sends for ``list[Any]``.

Gemini's ``enum`` holds strings only, so an ``enum`` of numbers or booleans
(``Literal[1, 2, 3]``) fails inside ``FunctionDeclaration``. It is dropped and
its values move to the description; the node keeps its declared type, or
takes the one its values share, so the model still sends a number, the type
the channel checks the call against. A ``null`` member is ``nullable``.

:func:`function_declaration` builds a tool's declaration from the cleaned
schema for the text and Live paths alike, and names the tool when the SDK
still refuses it.
"""

from __future__ import annotations

import json
from typing import Any

from pydantic import ValidationError

from roomkit.providers.ai.base import ProviderError
from roomkit.providers.ai.tool_declaration import ToolNameRule, declared_parameters

GEMINI_TOOL_NAMES = ToolNameRule("gemini", r"[A-Za-z_][A-Za-z0-9_.:-]{0,127}")
"""The tool names Gemini accepts, a dot and a colon included, a leading digit
not (measured 2026-10-02)."""

# Fields that Gemini accepts in a function parameter schema.
_GEMINI_ALLOWED_KEYS = frozenset(
    {
        "type",
        "properties",
        "required",
        "description",
        "enum",
        "items",
        "format",
        "nullable",
        "minimum",
        "maximum",
        "minItems",
        "maxItems",
    }
)

_UNION_KEYS = ("anyOf", "oneOf", "allOf")


def clean_gemini_schema(schema: dict[str, Any] | None) -> dict[str, Any] | None:
    """Recursively prepare a JSON Schema for Gemini ``FunctionDeclaration``.

    Performs four passes per node:

    1. **Fold what Gemini cannot say.** A type list and a union become one
       type: ``{"anyOf": [{...}, {"type": "null"}]}`` and ``{"type": [...,
       "null"]}`` become ``{..., "nullable": true}``. A wider ``anyOf`` /
       ``oneOf`` keeps its first non-null branch, an ``allOf`` gathers the
       fields of all of them. A union that only narrows its node (see
       :func:`_refines_node`) is not folded; the node keeps the fields its
       branches add (see :func:`_keep_node`).
    2. **Spell out the shape** JSON Schema leaves implied: the type an
       untyped node's ``properties`` or ``items`` imply, ``items`` on an
       array, and no key the type cannot carry (see :func:`_complete_shape`).
    3. **Describe a non-string enum**, which Gemini cannot hold (see
       :func:`_describe_enum`).
    4. **Strip unknown keys.** Anything not in :data:`_GEMINI_ALLOWED_KEYS`
       (e.g. ``$schema``, ``additionalProperties``, ``default``, ``title``)
       is dropped at every nesting level, and ``required`` keeps only the
       properties that survived.

    Args:
        schema: A JSON Schema dict (e.g. tool parameter schema), or None.

    Returns:
        A cleaned copy, or None if input was None.
    """
    if schema is None:
        return None
    return _clean(schema)


def _collapse_union(obj: dict[str, Any]) -> dict[str, Any]:
    """If *obj* is a union schema, fold it down to a single branch.

    Handles ``anyOf``, ``oneOf``, ``allOf``. ``Optional[X]`` (the
    Pydantic shape ``[{type: X}, {type: null}]``) collapses to
    ``{type: X, nullable: True}``. Wider unions keep the first
    non-null branch and mark ``nullable`` if any branch was null; an
    ``allOf``, whose branches all apply, gathers their fields instead.
    A union that narrows *obj* leaves it whole.
    """
    union_key = next((k for k in _UNION_KEYS if isinstance(obj.get(k), list)), None)
    if union_key is None:
        return obj

    branches: list[dict[str, Any]] = [b for b in obj[union_key] if isinstance(b, dict)]
    if _refines_node(obj, branches):
        return _keep_node(obj, branches)
    has_null = any(b.get("type") == "null" for b in branches)
    non_null = [b for b in branches if b.get("type") != "null"]

    if not non_null:
        # Pure null union → fall back to a string nullable so the
        # property remains valid; should not happen in practice.
        merged: dict[str, Any] = {"type": "string", "nullable": True}
    else:
        merged = _intersect(non_null) if union_key == "allOf" else dict(non_null[0])
        if has_null:
            merged["nullable"] = True

    # Preserve description / other allowed keys from the parent.
    for key in ("description", "title", "nullable"):
        if key in obj and key not in merged:
            merged[key] = obj[key]
    # The branch can be a union itself: an Optional discriminated union is an
    # ``anyOf`` whose first branch is a ``oneOf``.
    return _collapse_union(merged)


def _refines_node(obj: dict[str, Any], branches: list[dict[str, Any]]) -> bool:
    """Whether a union narrows *obj* rather than offering alternative types.

    A node that declares its own ``properties`` or ``items`` has its shape; a
    union beside them can only add constraints to it (``required``
    alternatives, a conditional field, a ``minItems``). So is a union none of
    whose non-null branches names a shape: ``{"type": "string", "anyOf":
    [{"format": "date"}, ...]}`` is still a string. Only a union of typed
    branches on a node without a structure of its own, ``Optional[X]`` being
    the common one, is a choice to fold.
    """
    if "properties" in obj or "items" in obj:
        return True
    alternatives = [b for b in branches if b.get("type") != "null"]
    # An empty union, or null alone, narrows nothing either: it takes the
    # fold's typed fallback rather than leaving the node typeless.
    return bool(alternatives) and not any(_names_a_shape(b) for b in alternatives)


def _names_a_shape(branch: dict[str, Any]) -> bool:
    """A branch with a ``type``, or one that is a union itself."""
    return "type" in branch or any(isinstance(branch.get(k), list) for k in _UNION_KEYS)


def _keep_node(obj: dict[str, Any], branches: list[dict[str, Any]]) -> dict[str, Any]:
    """*obj* under a union that narrows it, with the fields its branches add.

    ``{"type": "object", "properties": {"mode": ...}, "oneOf": [{"properties":
    {"url": ...}, "required": ["url"]}, {"properties": {"path": ...}, ...}]}``
    offers ``url`` or ``path`` beside ``mode``. Gemini cannot say "one of", so
    every field a branch adds is declared and no branch's ``required`` is:
    only one of them applies. A field the node declares itself wins over a
    branch's narrowing of it. Only an object gains fields, or an untyped node
    without ``items``, which they make one (see :func:`_complete_shape`). A
    null branch keeps the node nullable, as the fold would.
    """
    kept = obj
    if any(b.get("type") == "null" for b in branches):
        kept = {**obj, "nullable": True}
    own = kept.get("properties", {})
    if kept.get("type", "object") != "object" or "items" in kept or not isinstance(own, dict):
        return kept
    properties = _gather_properties(own, branches)
    if len(properties) == len(own):
        return kept
    return {**kept, "properties": properties}


def _intersect(branches: list[dict[str, Any]]) -> dict[str, Any]:
    """The first branch of an ``allOf``, with every other branch's fields.

    All the branches of an ``allOf`` apply at once (a zod intersection, a
    model extending a mixin), so their properties and their ``required``
    both hold, where an ``anyOf`` offers one branch among several.
    """
    merged = dict(branches[0])
    own = merged.get("properties", {})
    properties = _gather_properties(own if isinstance(own, dict) else {}, branches)
    required: list[Any] = []
    for branch in branches:
        names = branch.get("required")
        if isinstance(names, list):
            required.extend(name for name in names if name not in required)
    if properties:
        merged["properties"] = properties
    if required:
        merged["required"] = required
    return merged


def _gather_properties(own: dict[str, Any], branches: list[dict[str, Any]]) -> dict[str, Any]:
    """*own* plus the properties *branches* add; a name *own* has wins."""
    properties = dict(own)
    for branch in branches:
        added = branch.get("properties")
        if isinstance(added, dict):
            for name, schema in added.items():
                properties.setdefault(name, schema)
    return properties


def _collapse_type_list(obj: dict[str, Any]) -> dict[str, Any]:
    """Fold a JSON Schema type *list* down to the single type Gemini takes.

    ``{"type": ["string", "null"]}`` is how JSON Schema spells an optional
    string, and Gemini's ``type`` is a single-valued enum — so the list has to
    become ``{"type": "string", "nullable": True}`` here or fail validation
    inside ``FunctionDeclaration``. Wider lists keep their first non-null
    member, matching how :func:`_collapse_union` treats a wider ``anyOf``:
    Gemini's dialect has no union type either way.
    """
    types_ = obj.get("type")
    if not isinstance(types_, list):
        return obj

    named = [t for t in types_ if isinstance(t, str)]
    non_null = [t for t in named if t != "null"]

    collapsed = dict(obj)
    # An all-null list would leave the property with no type at all, which is
    # what Gemini silently refuses to invoke; string keeps it declarable.
    collapsed["type"] = non_null[0] if non_null else "string"
    if len(named) != len(non_null):
        collapsed["nullable"] = True
    return collapsed


def _complete_shape(obj: dict[str, Any]) -> dict[str, Any]:
    """Spell out the type and ``items`` JSON Schema leaves implied.

    Gemini refuses ``properties`` on a node that is not an object ("only
    allowed for OBJECT type"), ``items`` on one that is not an array
    ("$type == Type.ARRAY"), and an array without ``items`` ("items: missing
    field") or with a tuple-style list of them, each with a 400 for the whole
    request. An untyped node takes the type its keys imply; a typed one loses
    the keys its type cannot carry.
    """
    kind = obj.get("type")
    if kind is None:
        kind = "object" if "properties" in obj else "array" if "items" in obj else None
    if kind is None:
        return obj
    shaped = {
        key: value
        for key, value in obj.items()
        if not (key == "items" and kind != "array")
        and not (key == "properties" and kind != "object")
    }
    shaped["type"] = kind
    if kind == "array" and not isinstance(shaped.get("items"), dict):
        shaped["items"] = {}
    return shaped


def _clean(obj: dict[str, Any]) -> dict[str, Any]:
    # A type list first, so a union sees the node's own single type (an
    # ``["object", "null"]`` node still gains the fields its union adds).
    obj = _collapse_type_list(obj)
    # Collapse union shapes BEFORE stripping unknown keys, so the union
    # members get inspected rather than silently discarded.
    obj = _collapse_union(obj)
    # And again for the branch the fold picked, whose own type list survives
    # the strip untouched (``type`` is allowed) and would fail inside Gemini.
    obj = _collapse_type_list(obj)
    obj = _complete_shape(obj)
    obj = _describe_enum(obj)

    result: dict[str, Any] = {}
    for key, value in obj.items():
        if key not in _GEMINI_ALLOWED_KEYS:
            continue
        if key == "properties" and isinstance(value, dict):
            result[key] = {k: _clean(v) for k, v in value.items() if isinstance(v, dict)}
        elif key == "items" and isinstance(value, dict):
            result[key] = _clean(value)
        else:
            result[key] = value
    return _keep_declared_required(result)


def _describe_enum(obj: dict[str, Any]) -> dict[str, Any]:
    """Move an ``enum`` Gemini cannot hold into the node's description.

    Gemini's ``enum`` is a list of strings: ``[1, 2, 3]``, ``[true]`` or a
    mix fail inside ``FunctionDeclaration``. Turning the values into strings
    would type the node a string, and the model's ``"2"`` would then fail the
    declared type the call's arguments are checked against. The node keeps its
    type, or takes the one all its values share, and its description names
    the values the declared ``enum`` allows. A ``null`` member, the JSON
    Schema spelling of an optional enum, becomes ``nullable``, so an enum of
    strings and ``null`` stays an enum.
    """
    values = obj.get("enum")
    if not isinstance(values, list):
        return obj
    present = [value for value in values if value is not None]
    nullable = {"nullable": True} if len(present) != len(values) else {}
    if present and all(isinstance(value, str) for value in present):
        return {**obj, "enum": present, **nullable} if nullable else obj
    described = {key: value for key, value in obj.items() if key != "enum"} | nullable
    if "type" not in described and (kind := _shared_json_type(present)) is not None:
        described["type"] = kind
    allowed = ", ".join(json.dumps(value, ensure_ascii=False, default=str) for value in values)
    description = described.get("description")
    note = f"Allowed values: {allowed}."
    described["description"] = f"{description} {note}" if description else note
    return described


def _shared_json_type(values: list[Any]) -> str | None:
    """The JSON type all *values* share, integers widening to numbers."""
    kinds = {_json_type(value) for value in values}
    if kinds == {"integer", "number"}:
        return "number"
    return kinds.pop() if len(kinds) == 1 else None


def _json_type(value: Any) -> str | None:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    return None


def function_declaration(
    types: Any,
    *,
    name: str,
    description: str | None,
    parameters: dict[str, Any] | None,
    **fields: Any,
) -> Any:
    """The ``FunctionDeclaration`` of one tool, its schema cleaned.

    A name Gemini refuses, or a schema the SDK still refuses, fails every
    turn that declares the tool, so either becomes a :class:`ProviderError`
    naming the tool rather than Gemini's 400 or the SDK's validation error,
    raised before the request's own error handling.
    """
    GEMINI_TOOL_NAMES.check([name])
    try:
        return types.FunctionDeclaration(
            name=name,
            description=description,
            parameters=clean_gemini_schema(declared_parameters(parameters)),
            **fields,
        )
    except ValidationError as exc:
        errors = exc.errors()
        first = errors[0] if errors else {}
        where = ".".join(str(part) for part in first.get("loc", ()))
        more = f" (+{len(errors) - 1} more)" if len(errors) > 1 else ""
        # Structural: a tool named ``context_length`` is not an overflow.
        raise ProviderError(
            f"Gemini cannot declare tool {name!r}: {where}: {first.get('msg', exc)}{more}",
            provider="gemini",
            context_overflow=False,
        ) from exc


def _keep_declared_required(result: dict[str, Any]) -> dict[str, Any]:
    """Drop the ``required`` names *result*'s ``properties`` do not define.

    Gemini refuses the request over such a name, and :func:`_clean` drops a
    property whose schema is not an object (a boolean ``true`` schema, say).
    An emptied list goes too: ``required`` on a node that is not an object is
    refused as well.
    """
    required = result.get("required")
    if not isinstance(required, list):
        return result
    declared = result.get("properties")
    declared = declared if isinstance(declared, dict) else {}
    kept = [name for name in required if isinstance(name, str) and name in declared]
    if kept:
        result["required"] = kept
    else:
        del result["required"]
    return result
