"""AI provider abstractions and mock implementation."""

from roomkit.providers.ai.base import (
    API_KEY_METADATA_KEY,
    AIContext,
    AIImagePart,
    AIMessage,
    AIProvider,
    AIResponse,
    AITextPart,
    AIThinkingPart,
    AITool,
    AIToolCall,
    AIToolCallPart,
    AIToolResultPart,
    ModelInfo,
    ModelPricing,
    ProviderError,
    ServedCall,
    StreamDone,
    StreamEvent,
    StreamTextDelta,
    StreamThinkingDelta,
    StreamToolCall,
    StreamToolCallDelta,
    is_context_overflow_message,
    some_vendor_accepts_tool_name,
    stream_call_of,
    thinking_parts_of,
    tool_call_of,
)
from roomkit.providers.ai.chat_request import OPENAI_CHAT, ChatDialect, chat_messages
from roomkit.providers.ai.image_parts import (
    image_part_base64,
    image_part_payload,
    image_part_uri,
)
from roomkit.providers.ai.json_schema import check_portable_schema, schema_mismatch
from roomkit.providers.ai.mock import MockAIProvider
from roomkit.providers.ai.model_tags import (
    SPEECH_CAPABILITY,
    TRANSCRIPTION_CAPABILITY,
    speech_tags,
    with_speech_tags,
)
from roomkit.providers.ai.response_schema import ResponseSchemaError
from roomkit.providers.ai.round_parts import RoundTranscript, round_parts
from roomkit.providers.ai.thinking_blocks import ThinkingBlocks
from roomkit.providers.ai.tool_calls import (
    CallIds,
    call_cut,
    call_garbled,
    call_partial,
    cut_call_error,
    is_truncation,
    partial_call_error,
    readable_arguments,
    tool_arguments,
    unreadable_arguments,
    unreadable_call_error,
)
from roomkit.providers.ai.tool_declaration import (
    ToolNameRule,
    chat_tool_declarations,
    declared_parameters,
)

__all__ = [
    "SPEECH_CAPABILITY",
    "TRANSCRIPTION_CAPABILITY",
    "API_KEY_METADATA_KEY",
    "AIContext",
    "AIImagePart",
    "AIMessage",
    "AIProvider",
    "AIResponse",
    "AITextPart",
    "AIThinkingPart",
    "AITool",
    "AIToolCall",
    "ServedCall",
    "AIToolCallPart",
    "AIToolResultPart",
    "CallIds",
    "ChatDialect",
    "MockAIProvider",
    "ModelInfo",
    "ModelPricing",
    "OPENAI_CHAT",
    "ProviderError",
    "ResponseSchemaError",
    "RoundTranscript",
    "StreamDone",
    "StreamEvent",
    "StreamTextDelta",
    "StreamThinkingDelta",
    "StreamToolCall",
    "StreamToolCallDelta",
    "ThinkingBlocks",
    "ToolNameRule",
    "call_cut",
    "call_garbled",
    "call_partial",
    "chat_messages",
    "chat_tool_declarations",
    "check_portable_schema",
    "cut_call_error",
    "declared_parameters",
    "image_part_base64",
    "image_part_payload",
    "image_part_uri",
    "is_context_overflow_message",
    "is_truncation",
    "partial_call_error",
    "readable_arguments",
    "round_parts",
    "schema_mismatch",
    "some_vendor_accepts_tool_name",
    "speech_tags",
    "stream_call_of",
    "thinking_parts_of",
    "tool_arguments",
    "tool_call_of",
    "unreadable_arguments",
    "unreadable_call_error",
    "with_speech_tags",
]
