"""AI provider abstractions and mock implementation."""

from roomkit.providers.ai.base import (
    API_KEY_METADATA_KEY,
    AIContext,
    AIImagePart,
    AIMessage,
    AIProvider,
    AIResponse,
    AITextPart,
    AIThinkingPart,
    AITool,
    AIToolCall,
    AIToolCallPart,
    AIToolResultPart,
    ModelInfo,
    ModelPricing,
    ProviderError,
    StreamDone,
    StreamEvent,
    StreamTextDelta,
    StreamThinkingDelta,
    StreamToolCall,
    StreamToolCallDelta,
    is_context_overflow_message,
)
from roomkit.providers.ai.image_parts import (
    image_part_base64,
    image_part_payload,
    image_part_uri,
)
from roomkit.providers.ai.json_schema import check_portable_schema
from roomkit.providers.ai.mock import MockAIProvider
from roomkit.providers.ai.response_schema import ResponseSchemaError

__all__ = [
    "API_KEY_METADATA_KEY",
    "AIContext",
    "AIImagePart",
    "AIMessage",
    "AIProvider",
    "AIResponse",
    "AITextPart",
    "AIThinkingPart",
    "AITool",
    "AIToolCall",
    "AIToolCallPart",
    "AIToolResultPart",
    "MockAIProvider",
    "ModelInfo",
    "ModelPricing",
    "ProviderError",
    "ResponseSchemaError",
    "StreamDone",
    "StreamEvent",
    "StreamTextDelta",
    "StreamThinkingDelta",
    "StreamToolCall",
    "StreamToolCallDelta",
    "check_portable_schema",
    "image_part_base64",
    "image_part_payload",
    "image_part_uri",
    "is_context_overflow_message",
]
